name: kavach
description: Kavach - Spam Alert App


publish_to: 'none'




version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_native_splash: ^2.3.1
  image: ^4.0.17
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: '#f7f6f1'
  color_dark: '#272727'
  image: assets/images/logo.png
  image_dark: assets/images/logo.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#f7f6f1"
    image-dark: assets/images/logo.png
    icon-background-color-dark: "#272727"

flutter:
  assets:
    - assets/images/
    - assets/images/on_boarding_images/on-boarding-image.png


  uses-material-design: true


  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
